### ISSUE TITLE
Subscribe group of devices for outbound Mapping

### ISSUE THREAD

**Issue by vdiwe** [SoftwareAG/cumulocity-dynamic-mapper#199]
Hi Team

For outbound mapping, We should have an option for a group subscription? Subscribing to devices individually would be quite tedious for customers.

**Comment by switschel** [comment]
Two ways how this can be achieved:

1. Create Subscriptions on groups directly - Might have the limitation that it will only work for alarms and events according the API documentation: https://www.cumulocity.com/api/core/#operation/postNotificationSubscriptionResource
2. Provide a REST endpoint which accepts Group MOs, traverse all it's children and create subscriptions once again on device level each.

I would prefer the 2nd option due to the API limitation of option 1.

**Comment by switschel** [comment]
Will be fixed with the next release  https://github.com/SoftwareAG/cumulocity-dynamic-mapper/commit/84e8127a3051853d6f3a4c1f555561f55895c5d7

**Comment by switschel** [comment]
Added with release [4.4.0](https://github.com/SoftwareAG/cumulocity-dynamic-mapper/releases/tag/v4.4.0)
